name: stats-reporting-test
on:
  push:
    branches:
    - master


jobs:
  report-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create stats file
        run: echo ${{ github.sha }} > stats.txt

      - name: Upload stats file to artifacts
        uses: actions/upload-artifact@v2
        with:
           name: master-stats
           path: ./stats.txt
           retention-days: 20
