name: download articats from master
on:
  pull_request


jobs:
  fetch-stats:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Download base artifact
       uses: dawidd6/action-download-artifact@v2
       with:
          name: master-stats
          path: ./base/
          commit:  ${{ github.event.pull_request.base.sha }}
          workflow: artifact-upload-master.yml

     - name: report stats file
       run: |
         ls -l
         cat ./base/stats.txt


