name: articats push master
on:
  push:
    branches:
    - master


jobs:
  report-stats:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create stats file
       run: echo ${{ github.sha }} > stats.txt


     - name: Reduce stats file size
       uses: sergeysova/jq-action@v2
       with:
          cmd: 'jq "{ assets: .assets}" ./data/master.json -r > ./data/master-small.json' 
     - name: Upload stats file to artifacts
       uses: actions/upload-artifact@v2
       with:
          name: master-stats
          path: ./data/master-small.json
          retention-days: 20
