name: stats-reporting-test
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]


jobs:
  report-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract editor's bundle size
        uses: sergeysova/jq-action@v2
        id: editor-size
        with:
          cmd: jq ".entrypoints.editor.assetsSize" data/stats.json -r

      - name: Extract player's bundle size
        uses: sergeysova/jq-action@v2
        id: player-size
        with:
          cmd: jq ".entrypoints.player.assetsSize" data/stats.json -r

            ${{ steps.version.outputs.value }}
      - name: send-stats
        run: |
          echo "player's size: ${{ steps.player-size.outputs.value }}"
          echo "editor's size: ${{ steps.editor-size.outputs.value }}"
          echo curl \
              --header "Authorization: Token ${{ secrets.seriesci_token }}" \
              --header "Content-Type: application/json" \
              --data "{
                \"values\":[
                  {
                      \"line\":\"player\",
                      \"value\":\"${{ steps.player-size.outputs.value }}\"
                  },
                  {
                      \"line\":\"editor\",
                      \"value\":\"${{ steps.editor-size.outputs.value }}\"
                  }
                ],
                \"sha\":\"${GITHUB_SHA}\"
              }" \
              https://seriesci.com/api/${GITHUB_REPOSITORY}/bundlessize/many
          curl \
              --header "Authorization: Token ${{ secrets.seriesci_token }}" \
              --header "Content-Type: application/json" \
              --data "{
                \"values\":[
                  {
                      \"line\":\"player\",
                      \"value\":\"${{ steps.player-size.outputs.value }}\"
                  },
                  {
                      \"line\":\"editor\",
                      \"value\":\"${{ steps.editor-size.outputs.value }}\"
                  }
                ],
                \"sha\":\"${GITHUB_SHA}\"
              }" \
              https://seriesci.com/api/${GITHUB_REPOSITORY}/bundlessize/many
