name: title check

on:
  pull_request:
    branches: [ master ]
    types:
      - opened
      - reopened
      - edited

jobs:
  Check_ticket:
    # if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: glowwVideo/ticket-check-action@v0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketPrefix: 'SPTL-'
          titleRegex: 'SPTL-(?<ticketNumber>\d+|NA)'
          branchRegex: 'SPTL-(?<ticketNumber>\d+)'
          bodyRegex: 'SPTL-(?<ticketNumber>\d+)'

